#!c:\users\alanm\desktop\projects\cardiovascular-analysis\cardiovascular-analysis\scripts\python.exe

from jupyter_nbextensions_configurator.application import main

if __name__ == '__main__':
    main()
